---
# tasks file for zabbix-agent
- name: Install Zabbix Agent
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian11_all.deb

- name: Install Zabbix Agent2
  ansible.builtin.apt:
    name: zabbix-agent2
    state: present
    update_cache: yes

- name: Install Zabbix Agent Plugin
  ansible.builtin.apt:
    name: zabbix-agent2-plugin-*
    state: present

- name: Restart Zabbix Agent 
  service:
    name: zabbix-agent2
    state: restarted
    enabled: yes
